name: Deployment Workflow exercise1
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
      - name: Run lint
        run: npm run lint
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying Project ..."