name: Deployment Workflow exercise1
on: [push, workflow_dispatch]
jobs:
  lint:
    run-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@4
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  test:
    needs: lint
    run-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@4
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
  deploy:
    needs: test
    run-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@4
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying Project ..."